import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FramerMotionProvider } from "@/utils/providers/FramerMotionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`h-screen ${inter.className}`}>
        <div className="flex h-full flex-col">
          <Header />
          <main className="flex-grow overflow-hidden">
            <FramerMotionProvider>{children}</FramerMotionProvider>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
